apiVersion: v1
kind: Secret
metadata:
  name: aks-access-test-secrets
  namespace: ${NAMESPACE}
  labels:
    app: aks-access-test
type: Opaque
data:
  jira-url: ${JIRA_URL_BASE64}
  confluence-url: ${CONFLUENCE_URL_BASE64}
  jira-personal-token: ${JIRA_PERSONAL_TOKEN_BASE64}
  confluence-personal-token: ${CONFLUENCE_PERSONAL_TOKEN_BASE64}
